default: &default
<% if ENV["DB_GEM"] == "mysql2" %>
  adapter: mysql2
  database: paper_trail_association_tracking_test
<% elsif ENV["DB_GEM"] == "pg" %>
  adapter: postgresql
  database: paper_trail_association_tracking_test
<% else %>
  adapter: sqlite3
  database: db/test.sqlite3
<% end %>

development:
  <<: *default

test:
  <<: *default
